spring.application.name=API-limiter
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.repositories.enabled=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/api_limiter}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html

app.cors.allowed-origins=${FRONTEND_ORIGIN:http://localhost:5173,http://localhost:3000}
app.jwt.secret=${JWT_SECRET:replace-me-with-a-very-long-local-development-secret-12345}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:36000000}
