CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    api_key VARCHAR(36) NOT NULL UNIQUE,
    plan VARCHAR(20) NOT NULL CHECK (plan IN ('FREE', 'GOLD'))
);
